parameters:
    app.version: '%env(resolve:APP_VERSION)%'
    app.host: '%env(resolve:APP_HOST)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude: '../src/{*DTO.php,*Exception.php}'

    # infrastructure
    # telegram bot
    App\Infrastructure\TelegramBot\Factory\TelegramBotClientFactoryInterface:
        alias: App\Infrastructure\TelegramBot\Factory\TelegramBotClientLoggingDecoratorFactory
    App\Infrastructure\TelegramBot\Factory\TelegramBotClientLoggingDecoratorFactory:
        decorates: App\Infrastructure\TelegramBot\Factory\TelegramBotClientFactory
    App\Infrastructure\TelegramBot\Factory\TelegramBotClientFactory: ~
    # imap
    App\Infrastructure\Imap\Factory\ImapClientFactoryInterface:
        alias: App\Infrastructure\Imap\Factory\ImapClientLoggingDecoratorFactory
    App\Infrastructure\Imap\Factory\ImapClientLoggingDecoratorFactory:
        decorates: App\Infrastructure\Imap\Factory\ImapClientFactory
    App\Infrastructure\Imap\Factory\ImapClientFactory: ~
    # persistence
    # repositories
    App\Infrastructure\Persistence\Doctrine\Repository\MailTelegram\MailTelegramRepository:
        class: App\Infrastructure\Persistence\Doctrine\Repository\MailTelegram\MailTelegramRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - App\Domain\Entity\MailTelegram\MailTelegram

    # domain
    # repositories
    App\Domain\Repository\MailTelegram\MailTelegramRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\MailTelegram\MailTelegramRepository

    # application
    # event listeners
    App\Application\Http\API\EventListener\APIRequestAuthenticationListener:
        tags:
            - { name: 'kernel.event_listener', event: kernel.request, method: onKernelRequest, priority: 100 }
        arguments:
            $tokenAuthenticator: '@app.token_authenticator.api'
    App\Application\Http\TelegramBot\EventListener\TelegramBotRequestAuthenticationListener:
        tags:
            - { name: 'kernel.event_listener', event: kernel.request, method: onKernelRequest, priority: 100 }
        arguments:
            $tokenAuthenticator: '@app.token_authenticator.telegram_bot'

    # handlers
    App\Application\Http\API\Handler\Version\GetVersionHandler:
        arguments:
            $version: '%app.version%'
    # commands
    App\Application\Command\MailTelegram\MailTelegramMessageForwarderCommand:
        arguments:
            $retriesCount: '%env(resolve:MAIL_TELEGRAM_FORWARDER_RETRIES_COUNT)%'
    # services
    App\Application\Service\Auth\TokenAuthenticatorInterface: ~
    app.token_authenticator.api:
        class: App\Application\Service\Auth\TokenAuthenticator
        arguments:
            $token: '%env(resolve:API_AUTH_TOKEN)%'
    app.token_authenticator.telegram_bot:
        class: App\Application\Service\Auth\TokenAuthenticator
        arguments:
            $token: '%env(resolve:TELEGRAM_BOT_AUTH_TOKEN)%'
    App\Application\Service\MailTelegram\Formatter\MailTelegramMessageFormatterInterface:
        alias: App\Application\Service\MailTelegram\Formatter\MailTelegramMessageFormatter
    App\Application\Service\MailTelegram\Formatter\MessageHeader\MailTelegramMessageHeaderFormatterInterface:
        alias: App\Application\Service\MailTelegram\Formatter\MessageHeader\MailTelegramMessageHeaderFormatter
    App\Application\Service\MailTelegram\Formatter\MessageHeader\MailTelegramMessageHeaderFormatter:
        arguments:
            $htmlTagSymbolsSanitizer: '@App\Application\Service\MailTelegram\Formatter\Sanitizer\HtmlTagSymbolsSanitizer'
    App\Application\Service\MailTelegram\Formatter\MessageBody\MailTelegramMessageBodyFormatterInterface:
        tags: [ 'app.mail_telegram_message_body_formatter' ]
    App\Application\Service\MailTelegram\Formatter\MessageBody\MailTelegramMessageBodyHtmlFormatter:
        arguments:
            $htmlTagSymbolsSanitizer: '@App\Application\Service\MailTelegram\Formatter\Sanitizer\HtmlTagSymbolsSanitizer'
        tags:
            - { name: 'app.mail_telegram_message_body_formatter', priority: 100 }
    App\Application\Service\MailTelegram\Formatter\MessageBody\MailTelegramMessageBodyTextFormatter:
        tags:
            - { name: 'app.mail_telegram_message_body_formatter', priority: 90 }
    App\Application\Service\MailTelegram\Formatter\MessageBody\MailTelegramMessageBodyFormatterRegistry:
        arguments:
            $formatters: !tagged_iterator app.mail_telegram_message_body_formatter
    App\Application\Service\MailTelegram\Formatter\Sanitizer\HtmlTagSymbolsSanitizer: ~
    App\Application\Service\MailTelegram\Forwarder\MailTelegramMessageForwarder: ~
    App\Application\Service\TelegramBot\Command\MailTelegram\CreateMailTelegramCommand:
        calls:
            - [ 'setRegistry', [ '@App\Application\Service\TelegramBot\Registry\TelegramBotClientRegistry' ] ]
    App\Application\Service\TelegramBot\Registry\TelegramBotClientRegistry:
        arguments:
            $telegramBotConfig:
                'mail_telegram_forwarder':
                    'telegram_bot_token': '%env(resolve:MAIL_TELEGRAM_FORWARDER_BOT_TOKEN)%'
                    'webhook_host': '%app.host%'
                    'webhook_uri': '/telegram-bot/webhook/mail-telegram'
                    'commands':
                        - '@App\Application\Service\TelegramBot\Command\MailTelegram\CreateMailTelegramCommand'
